### ISSUE TITLE
Uncaught TypeError: __webpack_require__.i(...) is not a function

### ISSUE THREAD

**Issue by uzairalam15** [storybooks/react-treebeard#146]
I am getting this error when I upgraded to 3 version of react-treebeard. I had to switch to 2.1.0.

Error: Uncaught TypeError: __webpack_require__.i(...) is not a function

Code: I was using the example code from the readme file

**Comment by maximilianoforlenza** [comment]
Hi @uzairalam15. Do you have the same error yet? I can't reproduce this.
